name: deploy_ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn && yarn run dist
      - name: deploy
        run: |
          cd dist

          # 如果是发布到自定义域名
          echo 'blog.ccoder.cc' > CNAME

          git init
          git config user.email "congccoder@gmail.com"
          git config user.name "ccoderJava"
          git add -A
          git commit -m "action:`date`"

          git push -f https://ccoderjava:${{ secrets.CCODERJAVA_BLOG }}@github.com/ccoderjava/ccoderjava.github.io.git master

<<<<<<< HEAD
=======
          git push -f https://ccoderjava:${{ secrets.CCODERJAVA_BLOG }}@github.com/ccoderjava/ccoderjava.github.io.git master
>>>>>>> af84c70f555cf18b6e6f39a0bcf5cb3438a74057
