name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn && yarn run dist
      - name: deploy
        run: |
          cd dist

          # 如果是发布到自定义域名
          echo 'blog.ccoder.cc' > CNAME

          git init
          git config user.email "congccoder@gmail.com"
          git config user.name "ccoderJava"
          git add -A
          git commit -am "auto deploy from action `date`"
          git push -f https://ccoderJava:${{ secrets.BLOG_ACCESS_TOKEN }}@github.com/ccoderJava/ccoderJava.github.io.git master
