name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn && yarn run dist
      - name: deploy
        run: |
          cd dist

          # 如果是发布到自定义域名
          echo 'blog.ccoder.cc' > CNAME

          git init
          git config user.email "congccoder@gmail.com"
          git config user.name "congJava"
          git add -A
          git commit -m 'deploy'

          git push -f https://ccoderjava:${{ secrets.GIT_ACCESSTOKEN }}@github.com/ccoderjava/ccoderjava.github.io.git master
